### ISSUE TITLE
M1 Bowside Blade Handle

### ISSUE THREAD

**Issue by Seb-Walker** [13enedict/CCRC#1]
On one M1 bowside blade the feathering hand grip has become unglued and is slipping

**Comment by 13enedict** [comment]
This has been assigned to Rob LJ who is going to liaise with Jack LA

**Comment by 13enedict** [comment]
OK, we're now planning on getting this sorted by Oarsport as part of a big job

**Comment by 13enedict** [comment]
Replaced all the blade grips on the (now) M2 blades
