### ISSUE TITLE
CAM101 Lightning outrigger gate

### ISSUE THREAD

**Issue by CCRCJuniors** [13enedict/CCRC#14]
The gate on lightning needs to be replaced with new washers and bolt.

**Comment by 13enedict** [comment]
Does this apply to strokeside or bowside (or both)?

**Comment by CCRCJuniors** [comment]
Hi Benedict,
It's a single scull, if memory serves me correctly it was the rights use gate we managed to rescue the gate so just the bolt and washers are needed. We can fix it ourselves if you confirm that there is a bolt and washers. 

Cheers
T

**Comment by Git-Oryx** [comment]
Also get some new quick release bolts for the wing riggers as the current ones are a hassle/pain-in-the-a** to quick release.

They look something like this (not sure if you need specific ones but measure diameter ...etc):
![quickrelease](https://cloud.githubusercontent.com/assets/3437886/11001494/4aa5e858-849f-11e5-8438-28ceba5ae63b.png)

Or try soaking them in WD40 first!

**Comment by 13enedict** [comment]
I had a look at Lightning and put a new gate on. I also adjusted the gate pitch from 6˚ to 2˚. @Git-Oryx I'll take a look at the pins - I'll pop some white lithium on there which will probably be enough.

**Comment by CCRCJuniors** [comment]
Thank you! Service has never been so good :)

**Comment by 13enedict** [comment]
Happy to help :). I've applied white lithium grease to the pins. They seem pretty easy to remove now.
