### ISSUE TITLE
Brian 1x - Footplate not attached to bottom bracket (broke)

### ISSUE THREAD

**Issue by Git-Oryx** [13enedict/CCRC#15]
Broke last Sunday:

This needs fixing properly as it's screwed in to the plastic rather than correct wing nut fittings from footplate to bottom plastic stretcher brackets.

Not safe as you'll not be able to get your feet out if capsize.  Couldn't fix and not around this week to fix it myself.

**Comment by 13enedict** [comment]
OK, the adjuster channel had come loose - most of the screws were missing so I guess they've come out over time. I refitted the channel and re-screwed it down.

In addition:
- The foot plate was warped; this was replaced. 
- The stretcher bracket was out of adjustment; I correctly adjusted it.
- The bowside outrigger required lateral pitch calibration; this was zero'd.
- I inspected the seat track and applied white lithium
