### ISSUE TITLE
CAM013 Doreen position five foot plate securing point / runner

### ISSUE THREAD

**Issue by pworth68** [13enedict/CCRC#18]
At my position 5, The plastic / rubber foot plate runner  (the bit attached to the inside of the hull around which water was collecting, where the wing nut is that we need to loosen to be able slide the footplate up and down) is very degraded and splayed and makes adjusting the foot plate very difficult. I now have to remove the wing nut completely and take it off the sliding / captive bolt in order to move it.

**Comment by 13enedict** [comment]
I've had a look. The plastic runner is, as you say, damaged. We don't have any spares so I've turned it around. However, the real problem is that the bracket on the foot plate is bent. So the problem won't be much better, yet.

I also replaced some screws on shoes and the restraining laces

**Comment by pworth68** [comment]
TYVM

From:  Benedict <notifications@github.com>
Reply-To:  13enedict/CCRC
<reply+00e9e5723e002a70fe3121175389451e5826b4187009ac0392cf0000000112596c759
2a169ce06e62969@reply.github.com>
Date:  Tuesday, 10 November 2015 08:27
To:  13enedict/CCRC <CCRC@noreply.github.com>
Cc:  Paul Worth <pworth@doctors.org.uk>
Subject:  Re: [CCRC] Doreen position five foot plate securing point / runner
(#18)


I've had a look. The plastic runner is, as you say, damaged. We don't have
any spares so I've turned it around. However, the real problem is that the
bracket on the foot plate is bent. So the problem won't be much better, yet.

I also replaced some screws on shoes and the restraining laces


Reply to this email directly or view it on GitHub
<https://github.com/13enedict/CCRC/issues/18#issuecomment-155356760> .

**Comment by 13enedict** [comment]
I went to replace the bracket but it became clear the the footplate itself was damaged. 
![image](https://cloud.githubusercontent.com/assets/9012054/11563828/ec238c06-99cd-11e5-9252-34e09dcbeaad.png)
That should be a straight line, not heavily bent.

I have replaced the footplate and it flows really nicely now.
