### ISSUE TITLE
Doreen has a damaged bow ball

### ISSUE THREAD

**Issue by ghiret** [13enedict/CCRC#19]
Doreen's bowball has been damaged. I think it happened during the Rambo crew outing on Sunday 1st of November. I remember having a close encounter on the way to the reach and the bow ball being damaged at the end of the outing, but I don't know if it was damaged beforehand.

Paco.

**Comment by 13enedict** [comment]
Replaced bow ball

**Comment by 13enedict** [comment]
Replaced bow ball
