### ISSUE TITLE
Redeham and Weep refurbishment

### ISSUE THREAD

**Issue by LauraClack** [13enedict/CCRC#2]
Shopping list for Redenham refurb - I will get the girls to put it all in if you can order the bits

2 x pairs of slides
32 x Wheels
3 x Shoes Size 8

Ta

**Comment by 13enedict** [comment]
Thanks, Laura. I'll look in to this. For reference, can you list the problems with the slides, wheels and shoes that are on there?

Which slides and shoes are affected?

**Comment by LauraClack** [comment]
I can't remember which shoes, Def the 3 seat. All the slides and wheels need replacing, they is knackered!

Date: Tue, 6 Oct 2015 04:40:27 -0700

**Comment by 13enedict** [comment]
The wheels and slides have been ordered. I'll update you when they've arrived.

**Comment by 13enedict** [comment]
Just to clarify, you say here that you want 2 pairs of slides but said to me verbally that all 8 pairs need changing. Can you confirm?

**Comment by LauraClack** [comment]
Sorry my mistake - we do need 8 pairs of slides
Thanks for sorting this. Will complete a report for Laurie too

Date: Thu, 22 Oct 2015 03:34:57 -0700

**Comment by 13enedict** [comment]
Wheels and slides have arrived. I'm planning on handing the parts over to Ursala to handle the fitting etc.

**Comment by LauraClack** [comment]
Thanks benedict,

Ursula I have pencilled in Saturday 31st as boat fixing day. Suggesting we do an outing at 8am then all hands on redeham and Laurie for cleaning and fixing the new bits as well as filling the whole on Laurie.

I'll get all the girls down if that works with you?

Laura

**Comment by LauraClack** [comment]
Hey, I have to run after rowing Saturday, I am going to Ely for the day. I
could do Sunday or prep something in advance?

**Comment by umarndt** [comment]
if I remember correctly, we should also check the stroke rigger (prev. reported but not logged)

**Comment by LauraClack** [comment]
Yep, need to check all the riggers and the rigging to make sure it's correct. I can do that if you can get the girls scrubbing!

**Comment by umarndt** [comment]
I would like to learn the technical part, I am sure we'll get people to
wash. I will also exchange the parts Ben will lend me tools.

**Comment by LauraClack** [comment]
Perfect!

**Comment by 13enedict** [comment]
Both,

Would you mind having a good look at the shoes / footplates situation while you're at it? Laura, can you confirm that you want 3 x Neaves adjustable rowing shoes size 8? They say they have about 4 sizes worth of adjustment.

**Comment by LauraClack** [comment]
Yes 3 pairs please, will have a good look at the rest. We're also auditing laurie so will check all the bits on that too. Will also fill the hole in the bow. You still have the filer on your desk right?

**Comment by 13enedict** [comment]
No idea, I haven't looked through that stuff. There's enough assorted solvents to make you forget your troubles, though. Check the top shelf.

**Comment by LauraClack** [comment]
I'll have a look tomorrow, can get some if you don't have the right stuff. Think I have some in the shed too.

**Comment by 13enedict** [comment]
OK, great, let me know if we need some. Please can you make sure you show Ursula what's involved. I would be interested myself but I will be away :(

**Comment by LauraClack** [comment]
Hi,

We have scrubbed redeham within an inch of its life. It looks fab! I have taken out the shoes that need replacing. They are on your bench, if you can put the new shoes into the plates we'll put them in the boat on Tuesday. 

There are a few holes in redeham that need filling that we noticed today. Also want to check the rig on it at some point soon. 

Hole in Laurie is filled. Just needs sanding down. We will scrub and audit Laurie next weekend or the week after. 

Laura

**Comment by LauraClack** [comment]
Hi, please can we also have some new gates for redeham? I noticed today that they are really worn. 

Thanks

Laura

**Comment by 13enedict** [comment]
Oh good, looking forward to seeing our Cinderella boat!

I've changed the two pairs of shoes I found in the workshop (it kind of reminds me of the shoemaker's elves). We haven't got new ones yet so I used what we had in stock; while they're not new but they are in good condition.

We should already have gates but please could you log the gates, holes and any rigging issues in separate issues?

Otherwise, I'll leave this issue for Ursula to close.
