### ISSUE TITLE
Outrigger cracked on CAM013 Doreen

### ISSUE THREAD

**Issue by 13enedict** [13enedict/CCRC#24]
The wing outrigger for the 5 seat has cracked open and is close to shearing off

**Comment by 13enedict** [comment]
I've had this repaired by Milton Precision Engineering however, it might be worth considering a replacement outrigger as it's been repaired before. The new outrigger is unpainted.

**Comment by Robllewellynjones** [comment]
I'd get a new one!

Sent from Outlook




On Fri, Nov 27, 2015 at 7:29 AM -0800, "Benedict" <notifications@github.com> wrote:












I've had this repaired by Milton Precision Engineering however, it might be worth considering a replacement outrigger as it's been repaired before. The new outrigger is unpainted.

**Comment by JackLA** [comment]
I've spoken to Stampfli and I'm working on a whole new 8 riggers as it's an
on going claim with them since 2011
