### ISSUE TITLE
CAM113 Green Stämpfli - Bow rigger backstay

### ISSUE THREAD

**Issue by CCRCJuniors** [13enedict/CCRC#25]
The back stay on the bow rigger of the green sampfli 2- is only held on by a nut and bolt, not a proper fixing and keeps coming loose.  Could it be secured with a proper fixing?
Many thanks
Tammy

**Comment by 13enedict** [comment]
Is this CAM202 John Henry?

**Comment by CCRCJuniors** [comment]
Hi Benedict 

No, I don't think it has a name, it's the pair that is stored in the back of the CRA where robs keep their boats. 

Cheers
Tammy

**Comment by 13enedict** [comment]
I had a look at the riggers. The rigging does look a tad dubious but I'm not sure I understood your specific concern.

It looks like the bowside backstay is held on to the boat uses a headless bolt with a nut on either side. Is this the situation you are referring to? I would assume that this should have a regular machine screw and a bolt

**Comment by CCRCJuniors** [comment]
Hi Benedict,

That is correct, when you put any pressure through the rigger the nut seems to loosen quite easily. Would be great if we could get the proper fixing. 
I don't want to be out with 16yr olds in a pair and the rigger come off :) 

Many thanks for looking into this.

Tammy

**Comment by 13enedict** [comment]
OK, I've fitted a proper bolt, see how that goes!
