### ISSUE TITLE
Benny Powell - seat rail at bow seat needs replacing

### ISSUE THREAD

**Issue by abarp** [13enedict/CCRC#27]
Seat rail at bow seat needs replacing
Right shoe at bow seat too small (different from left shoe) - needs replacing

**Comment by 13enedict** [comment]
We've got the necessary spare parts in now. They need drilling, sanding and painting which should be done for Saturday. If you're planning on using the boat would you let me know so we can put it all together?

**Comment by abarp** [comment]
Hi

Yes thank you. I will ping the crew now to check availability, so if all
are available, we would like to go out on Sat Morning.

Thank you very much for looking into this.

Cheers

Andrea

**Comment by abarp** [comment]
Hi Benedict,

We have a crew for Saturday, so if you can work on the boat, that would be
awesome. Let us know if you need anything from us.

Cheers

Andrea

**Comment by abarp** [comment]
Hi Benedict

Just checking if it's all good with Benny Powell for tomorrow morning. If
anything needs doing tomorrow morning, we could have a look into it
tomorrow morning.

Cheers

Andrea

**Comment by 13enedict** [comment]
The boat isn't booked out. What time are you planning on using it? I'll need you guys to move it on to trestles to finish the boat off but it should only take 15 minutes.

**Comment by abarp** [comment]
Hi

I haven't booked it because I did not know if it was rowable. I also tried
to book now, but it doesn't allow me. ..We are planning to go out at 8.

Cheers

Andrea

**Comment by abarp** [comment]
OK, I’ll be there from 7:30 ish

**Comment by abarp** [comment]
thank you so much. See you tomorrow morning.


A

**Comment by abarp** [comment]
Running a little late.

A

**Comment by abarp** [comment]
I think we are all late. But we are on our way. Sorry.

A

**Comment by 13enedict** [comment]
Replaced track inserts

**Comment by abarp** [comment]
hi

thanks a lot for your help!

A
