### ISSUE TITLE
Ralf stroke shoes are tiny. 

### ISSUE THREAD

**Issue by JohnLeighton** [13enedict/CCRC#275]
Ralf

The shoes in the stroke seat are tiny. Please can they be swapped with some men's sized shoes. 

Stroke seat

**Comment by NSinclair94** [comment]
I take great offense to this. 
However, I will set aside a pair of shoes for you to put in Ralf.

**Comment by JohnLeighton** [comment]
?Time for me to start making jokes about big feet and other parts of the body.  Unfortunately, you've seen me in lycra, so you know it's a lie.


___________________________
John Leighton
Mobile +44 7717 824 931
________________________________
