### ISSUE TITLE
Doreen - loose (centre) runner in seat 4

### ISSUE THREAD

**Issue by Terywall** [13enedict/CCRC#276]
### Boat name or ID
enter the boat name or ID here - Doreen

### Problem description
enter problem description here, please provide as much information as possible - the centre runner has come away.  The thread has gone on all excerpt one screw which is currently keeping it in place.  I suspect it needs to be glued down. 

### Seat number(s) affected
specify the seats affected (or remove if not applicable) - seat 4

### Photos of the issue
put a photo of the issue here

**Comment by Terywall** [comment]
![image](https://user-images.githubusercontent.com/28512643/41924765-c78e1448-7962-11e8-9e87-eda916faf273.png)

**Comment by NSinclair94** [comment]
There are screws, tighten it

**Comment by 13enedict** [comment]
Move it and create new threads

**Comment by Terywall** [comment]
Nick - none of us are that lazy or daft enough not to try screwing it in first...

Benedict - thanks.  I’ll try that.  We didn’t want to just pierce holes without checking with you guys first.  That should hopefully fix it.

**Comment by NSinclair94** [comment]
Make sure they're lined up properly

**Comment by 13enedict** [comment]
Assuming this is fixed...?

**Comment by Terywall** [comment]
All fixed now - thanks
