### ISSUE TITLE
Tailwind bow seat

### ISSUE THREAD

**Issue by pworth68** [13enedict/CCRC#277]
Tailwind

2 issues at bow seat:

1. Runners / wheels very gritty / bumpy about half way up the slide

2. Gate is wobbling up and down on the pin. Needs another washer / spacer

### Seat number(s) affected
specify the seats affected (or remove if not applicable)

### Photos of the issue
put a photo of the issue here (or remove if not applicable)

**Comment by NSinclair94** [comment]
If you weren't rowing for robs this bumps, I would fix it right away ;)

**Comment by pworth68** [comment]
News travels fast!

**Comment by NSinclair94** [comment]
Thank you for reporting it though, will get round to it this weekend
