### ISSUE TITLE
Kieran West: seat 5- footplate broken 

### ISSUE THREAD

**Issue by umarndt** [13enedict/CCRC#279]
### KW
###footplate broken

**Comment by umarndt** [comment]
reported by M4 (we went through and everyone checked their seat)
various issues regarding bad shoes and loose shoes is being fixed by crew. contact @eyal  for more details.

**Comment by NSinclair94** [comment]
Didn't see anything to suggest it was broken today, just looks like the shoes need replacing

**Comment by umarndt** [comment]
The connector between the centre screw and the rest of the footplate is missing.

**Comment by ghost** [comment]
This is the 6 seat, not the 5 seat.  I also just reported it.  Jess

**Comment by eyalpole** [comment]
Solved 👍
