### ISSUE TITLE
CAM409 Liberty steering cable

### ISSUE THREAD

**Issue by DMB1** [13enedict/CCRC#28]
Steering cable snapped at the bow footplate. Boat required for Christmas Head please, thanks.

**Comment by 13enedict** [comment]
I've replaced the rubbish extant cable with a new one but I haven't fully adjusted it and there's a lot of slack in the cable. Should be able to finish for Saturday.

**Comment by DMB1** [comment]
Thanks, much appreciated, the juniors will now be able to use to for the Christmas Head.
David
