### ISSUE TITLE
Reedham 4 & 5seats

### ISSUE THREAD

**Issue by bjarr21** [13enedict/CCRC#282]
Reehem

### Problem description
4 seat- the left runner/track needs to have the cap put on.  Benedict helped us replace the damaged runner, but there is not a cap for it.  As a result, it will cut the leg of the person sitting in 4 seat.  It is very painful!!
5 seat- right runner was fixed, but there is a large hole where the bolt anchors the track to the boat and the bolt is coming off, potentially the hole is getting larger.  Discovered when we tried to adjust the slides/runners.

### Seat number(s) affected
4 and 5

### Photos of the issue
put a photo of the issue here (or remove if not applicable)

**Comment by 13enedict** [comment]
This should be two separate issues. Grab me with a smallish Phillips / crosshead screwdriver for the first one. For the second this, it sounds like the bush is missing; we have spares.

**Comment by bjarr21** [comment]
Will do.  I believe W5 is using it for bumps.  A piece of tape was placed over 4's track to keep from drawing blood for now.

**Comment by NSinclair94** [comment]
No longer our problem

**Comment by bjarr21** [comment]
That's one way to deal with something...
