### ISSUE TITLE
Kieran West - 6 stretcher & Join

### ISSUE THREAD

**Issue by ghost** [13enedict/CCRC#284]
### Boat name or ID
Kieran West

### Problem description
Stretcher at 6 has sheered at bottom so footplate is only connected by 2 points above the feet, not connected at the heel. (Seb has photos)
Join of boat, between 6 and 7, started leaking as soon as it touched the water.  Couldn't see any obvious reason (we checked the join)

### Seat number(s) affected
6 / ALL

**Comment by eyalpole** [comment]
Re-connected, and not leaking on our last outing this evening, so fingers crossed!
