### ISSUE TITLE
CAM012 Kieran West Footplate - 3 seat

### ISSUE THREAD

**Issue by colmcmurphy** [13enedict/CCRC#29]
Good Sir,

3's foot plate on Kieran West needs some TLC. I believe the issue was that the shoe(s) had detached from the plate itself, as opposed to the plate detaching from the boat. 

The Cobra crew would be eternally grateful for your assistance with this matter.

**Comment by 13enedict** [comment]
Had a look at all the shoes; a few were loose and one or two are a bit buggered. I've botched them for now but I'll look in to getting some new pairs. Footplates, I now realise, are a bit of pain as well.

**Comment by colmcmurphy** [comment]
Thanks Benedict.
