### ISSUE TITLE
Tailwind damage to hull at bow end

### ISSUE THREAD

**Issue by gdg23** [13enedict/CCRC#291]
### Boat name or ID
Tailwind

### Problem description
The bows ended up on the hard as we came in to park. The hull has been scraped along the bottom and is actually split lengthways (as in water would now be soaked into the internal honeycomb). I may be wrong but it looks like this may have reopened/extended an existing split (there is some black tape which was already on the boat which may have been holding a similar split together). My assessment is that it should not be rowed until fixed.

**Comment by 13enedict** [comment]
What were the circumstances of the incident?

**Comment by NSinclair94** [comment]
Can this be de-rigged tonight.
Need to arrange a repair

**Comment by NSinclair94** [comment]
A new issue has been created for this
