### ISSUE TITLE
Quad women's blade broken

### ISSUE THREAD

**Issue by danirodrin** [13enedict/CCRC#292]
### Boat name or ID
Women's quad blade (left side, blade with 3 stripes)

### Problem description
Got rammed by another single who was on the wrong side of the river coming out of green dragon. His name is Karel Kabelik from Nine's who said he would take responsibility for the damage, so feel free to contact him. The blade got damaged and I have placed it behind the singles at the front left side of the boathouse.

**Comment by NSinclair94** [comment]
Eugh... 
I will contact the captain of nines and try and sort something out.

**Comment by NSinclair94** [comment]
Didn't mean to close this

**Comment by NSinclair94** [comment]
When the next blade order come in nines will purchase one to replace the broken one
