### ISSUE TITLE
C&J missing 2 port lids

### ISSUE THREAD

**Issue by bjarr21** [13enedict/CCRC#294]
### Boat name or ID
C&J

### Problem description
Port lids missing from 2&3 seats

### Seat number(s) affected
2&3

### Photos of the issue
put a photo of the issue here (or remove if not applicable)

**Comment by bjarr21** [comment]
Any luck on finding ones that fit?

**Comment by NSinclair94** [comment]
There are some in the box behind corpus.
I can find them tomorrow
