### ISSUE TITLE
Chunk taken out of top of M2 blade

### ISSUE THREAD

**Issue by JohnLeighton** [13enedict/CCRC#297]
### Boat name or ID
M2 blade

### Problem description
Blade hit rudder of scull and took a fair chunk out the top.

### Seat number(s) affected
1 blade

**Comment by JohnLeighton** [comment]
Chuck was taken out the top of one stroke side blade following a clash with the rudder on another boat.

**Comment by NSinclair94** [comment]
Where are these blades now?

**Comment by JohnLeighton** [comment]
Aren't the M2 blades at Christs?  We used them yesterday and had a full set, so I assume someone has fixed it?

**Comment by NSinclair94** [comment]
No one seems to be able to find it so I'll close this until it's found
