### ISSUE TITLE
Benjamin 3 seat rigger very loose

### ISSUE THREAD

**Issue by JohnLeighton** [13enedict/CCRC#300]
Benjamin

Benjamin rigger has come loose on the 3 seat. Needs tightening and re-pitching

**Comment by NSinclair94** [comment]
What part of the rigger?
Was it the backstay?
You and guy are both menaces.

**Comment by JohnLeighton** [comment]
The pin went very loose - bolt nearly fell off. Backstay also very loose, which is why it probably needs the pitch checking.

john@johnleighton.co.uk
+44 7717 824 931

On 11 Oct 2018 19:16, NSinclair94 <notifications@github.com> wrote:

What part of the rigger?
Was it the backstay?
You and guy are both menaces.

-

**Comment by NSinclair94** [comment]
If you just tighten it for the time being I will check at the weekend when I replace the rudder

**Comment by JohnLeighton** [comment]
We didn't have tools with us tonight, but are going to take them on Saturday when we're out in it again.

john@johnleighton.co.uk
+44 7717 824 931

On 11 Oct 2018 19:38, NSinclair94 <notifications@github.com> wrote:

If you just tighten it for the time being I will check at the weekend when I replace the rudder

-

**Comment by stigweed** [comment]
The fillipi for riggers do rattle loose on their own. Frequently used to happen with Tony.

**Comment by NSinclair94** [comment]
Have you managed to sort this John?

**Comment by stigweed** [comment]
I don't think anyone's had any trouble with this recently.

**Comment by JohnLeighton** [comment]
No, we bought a big spanner and fixed it at the next outing.

**Comment by JohnLeighton** [comment]
No, we brought a big spanner and fixed it at the next outing.
