### ISSUE TITLE
Clams stock

### ISSUE THREAD

**Issue by stigweed** [13enedict/CCRC#301]
Can you order a few spare clams? We lost one on Sunday. It was warped and popped off, a few others are getting a bit old and wobbly. Not sure how many there are around, I think a stash went into the trinity box after pairs head) but a lot of small boats use so they're going to go missing eventually.
-Stu

**Comment by NSinclair94** [comment]
They are £2 each with £4.50 shipping. With that in mind, how many do you want?

**Comment by 13enedict** [comment]
A bazillion.

**Comment by stigweed** [comment]
Maybe 8 for now. I don't know what condition they're all in and at that
price it's probably not worth the effort of an audit.

**Comment by NSinclair94** [comment]
I have raised an invoice for 10. Interestingly Clam stands for Clip-on Loading Adjustment Mechanism.
Will close the issue when they arrive.
Benedict, is it ok to get these delivered to yours?

**Comment by 13enedict** [comment]
I assumed everyone knew the acronym. In principle, yes. I am out quite a
bit these days, though.

**Comment by NSinclair94** [comment]
They have arrived
