### ISSUE TITLE
Nut missing from John Henry

### ISSUE THREAD

**Issue by johnwalley** [13enedict/CCRC#302]
John Henry

### Problem description
Nut missing from screw used to attach bottom part of the footplate assembly to the track

### Seat number(s) affected
stroke

**Comment by NSinclair94** [comment]
was this still an issue on your outing yesterday?

**Comment by johnwalley** [comment]
Unknown. We decided it would be too difficult to get the shell unloaded and loaded from where it was on the trailer 😞

**Comment by NSinclair94** [comment]
Should be fine now
