### ISSUE TITLE
Ralph bow shoe footplate screws

### ISSUE THREAD

**Issue by HomMen** [13enedict/CCRC#303]
### Boat name or ID
enter the boat name or ID here
Ralph
### Problem description
enter problem description here, please provide as much information as possible
Bow seat shoe come off footplate. Screws needed to reattach.
### Seat number(s) affected
specify the seats affected (or remove if not applicable)
Bow seat

**Comment by NSinclair94** [comment]
All sorted, thanks Iain for raising the issue and helping me sort it.
Long term I will have to look to see if we can have all 4 screws in both the shoes.
