### ISSUE TITLE
W2 Blade Handles

### ISSUE THREAD

**Issue by bjarr21** [13enedict/CCRC#304]
W2 Blade Handles

the rubber grips have come loose.  When you are feathering at a high rate, the grip spins and you can't row properly.  We have taped them several times and the tape eventually gives way.  Too much tape and blisters form in the wrong places.

2 stroke side, 1 bow side.

### Photos of the issue
put a photo of the issue here (or remove if not applicable)

**Comment by NSinclair94** [comment]
The one which was labelled with white tape was fixed. Please mark them up or I won't fix them

**Comment by bjarr21** [comment]
The one that failed last night has green and yellow striped tape at the top
of the handle.  It is a strokeside blade and it is under C&J.

**Comment by NSinclair94** [comment]
Myself and Sarah have just fixed these on our days off. It is clear that these blades aren't being cared for properly as all of them have this problem. Please look after the equipment

**Comment by bjarr21** [comment]
I think you know me well enough to know that I am a stickler for caring for
equipment!!  I know that Homerton used our blades this week as well, so it
is not just us!  We have taped them up with the tape that we have- I assure
you we are not just putting things back without reporting/trying to fix or
abusing them!  If rate 34 is abuse, then I'd be happy to go slower.

**Comment by NSinclair94** [comment]
At no point did I say it was you, I'm merely stating that no other blade in the fleet has this problem, but somehow 7 have appears in the same set.
Also, a thank you would be nice...

**Comment by bjarr21** [comment]
The blades were great today.  A huge thank you to you and Sarah for
repairing those.  We really do appreciate it.

Also, my crew has sorted the hatch covers now.  Thank for facilitating that
with the materials, and thank you, Sarah, for leaving the stuff for us to
do it.
