### ISSUE TITLE
C&J Hatch Covers

### ISSUE THREAD

**Issue by bjarr21** [13enedict/CCRC#305]
Caroline and Joanne

Still need hatch covers or replacement kits for 2 seats.  The temporary ones do not actually fit and cannot be used on the Tideway.

2 & 3

### Photos of the issue
put a photo of the issue here (or remove if not applicable)

**Comment by NSinclair94** [comment]
Sunday night ~ 6pm have your crew get the boat out and I will do it then. Please be there on time as I hope to at least try and get an erg in that evening

**Comment by bjarr21** [comment]
3 of the 4 of us can be there- Holly will be in London right after our
morning outing.  Is there prep work we can do after our outing to speed up
the evening process?

**Comment by NSinclair94** [comment]
This has been taken care of, thank you Sarah!
