### ISSUE TITLE
Upstair erg computer is out of batteries

### ISSUE THREAD

**Issue by ghiret** [13enedict/CCRC#31]
One of the ergs control unit is out of battery and the light is off which makes it harder to see anything when it's later than 3pm. It's the one that's a different model to the other three.

**Comment by 13enedict** [comment]
That erg has a PM3 which isn't backlit. I checked the batteries and it seemed to be OK. What happened to make you think it's out of battery?

**Comment by 13enedict** [comment]
Close enough. Replaced the back of one of the PM5 units so that you can screw the battery plate on
