### ISSUE TITLE
Benny Powell: Stroke footplate needs replacing

### ISSUE THREAD

**Issue by SDArrigo** [13enedict/CCRC#313]
### Boat name or ID
Benny Powell

### Problem description
The holes for adjusting the height of the footplate for stroke seat are getting increasingly worn down and merging with each other, particularly on the right hand side. For the moment it's possible to screw the footplate in tight with pliers and it lasts for most of an outing. Maybe some washers would help protect the new footplate.

### Seat number(s) affected
Stroke

### Photos of the issue
![img-20181127-wa0000](https://user-images.githubusercontent.com/45421404/49144650-cd4bb400-f2f5-11e8-9822-d93c17c87bc1.jpg)
![img-20181128-wa0000](https://user-images.githubusercontent.com/45421404/49144658-d046a480-f2f5-11e8-81f5-cd753880cb76.jpg)

**Comment by NSinclair94** [comment]
Is this still an issue? I have spares

**Comment by adrianalexa** [comment]
yes, there are a couple of footplates in the boat that need replacement. How can we help to make this happen?

**Comment by NSinclair94** [comment]
If I put some out, can you change them for me? I will just make sure I have
enough now that Doreen needs some.

**Comment by adrianalexa** [comment]
Sure, no problem at all. I'll change and report back here. Can you leave with them a few show screws as well - maybe 5-6. I think some of the shoes are missing one screw. And if we get washers as well, I'll also make sure every plate will have washers under the butterflies. 

Where will I find the footplates?

**Comment by NSinclair94** [comment]
There are spare fittings (nuts,washers etc in the black box by the fours
rack

**Comment by NSinclair94** [comment]
Is this still an issue?

**Comment by SDArrigo** [comment]
Now sorted. You gave us a replacement plate and we put it in a few weeks ago. Thanks
