### ISSUE TITLE
Olive’s rudder wire

### ISSUE THREAD

**Issue by HCBC-Women** [13enedict/CCRC#314]
Olive

The rudder wire snapped in the middle of the outing we had yesterday. I have tried to tie the wire so that it does not get anymore damaged.

**Comment by NSinclair94** [comment]
I probably won't be able to get round to fixing this until the weekend, I'm happy for your equipment Officer to have a look at this?

**Comment by HCBC-Women** [comment]
Unfortunately everyone is gone back home - the undergraduates have to leave the college at the end of term.

Best,

**Comment by NSinclair94** [comment]
Thank you to Homerton to fixing this
