### ISSUE TITLE
Shoe plate damaged on Doreen

### ISSUE THREAD

**Issue by adrianalexa** [13enedict/CCRC#316]
### Boat name or ID
Doreen

### Problem description
The shoe plate for seat no. 7 is worn out. The screw pass throw the plate holes - screws tighten to the max. The left shoe basically holds itself into just one screw, and it wobbles a lot.

### Seat number(s) affected
no. 7

### Photos of the issue
![img_2467](https://user-images.githubusercontent.com/1910746/49549863-e948ea00-f8e1-11e8-9271-cd4519b7c308.jpeg)

**Comment by NSinclair94** [comment]
There are spare foot plates at the trinity hall rack.
