### ISSUE TITLE
CAM321 Redeham and Weep - damaged bowball

### ISSUE THREAD

**Issue by nathalieflower** [13enedict/CCRC#32]
Bow was damaged whilst spinning Reedham on Tuesday. 

Jack also mentioned that there was a big scratch on the shell, although I haven't seen it.

BW

N

**Comment by 13enedict** [comment]
Hmm. That's not a damaged bowball, that's a broken bow. Not sure if it will be available for use on Saturday at this rate.

**Comment by 13enedict** [comment]
Bowball has been replaced
