### ISSUE TITLE
Laurie: discrimination against the deaf

### ISSUE THREAD

**Issue by DarthSlater** [13enedict/CCRC#320]
Laurie Halifax

The ongoing speaker issue.  There is no speaker to service bow 3 so if you happen to sit there you can't hear a thing.  Turning it up results in 4 and 5 being deafened.  As it's going to wehorr this needs something 

Also no foot straps at 5 and the stroke meter doesn't work.  Apologies if this has all  been logged already

**Comment by 13enedict** [comment]
So, to fix this, we'll need it on trestles, near a power source to check all the wiring and possibly fix the connections, as well

**Comment by Terywall** [comment]
Can we arrange to do Doreen at the same time please which also has wiring issues (cox box plug needs changing).  I have arranged a 'boat maintenance session' from 09:00-10:00 on Sat 09/02 amongst our crews so we can give Doreen and Ralf some TLC - and wondered if we can get some of these issues looked at then?

**Comment by NSinclair94** [comment]
The speakers in the bow just need bolting onto the boat. I never got round to doing this. All thats needed for this is some screws and a drill.
When you say foot straps, do you mean the quick release, or the heel restraints?
As for the rate meter, I would suspect that there is something wrong with the orientation of the magnet on the stroke seat.

@Terywall would you be able to change the rudder on Benny Powell as well? Gytha mentioned that there was an issue and my initial look suggests that the current rudder has bent, so its catching on the boat.

**Comment by Terywall** [comment]
Sure NP - we'll take a look at BP's rudder.
