### ISSUE TITLE
Sculling baldes: screw adjustable inserts (Croker) needed

### ISSUE THREAD

**Issue by Git-Oryx** [13enedict/CCRC#324]
Croker blade (sculling)

Need an locking plate as screw is jammed in and can't get it out.  Not sure if you need to order one or there's a spare somewhere.

![IMG_2597 (Edited)](https://user-images.githubusercontent.com/3437886/55411971-7d5c5280-555e-11e9-89b0-cca9a9854425.JPG)

![IMG_2598](https://user-images.githubusercontent.com/3437886/55412026-95cc6d00-555e-11e9-9e6f-07ae3d539ae6.jpg)

**Comment by NSinclair94** [comment]
Think there is one laying about.
Thanks for this!

**Comment by Git-Oryx** [comment]
Can't remember if I fixed this.  It was the yellow handle with green/yellow stripes.  Will check tonight.
