### ISSUE TITLE
Hilary body de-attaching next to rigger

### ISSUE THREAD

**Issue by Karlovik** [13enedict/CCRC#325]
### Boat name or ID
Hilary

### Problem description
Body de-attaching next to rigger. Pretty clear when you give it a wobble. Don't think it's very rowable.

![IMG_20190409_085244](https://user-images.githubusercontent.com/10038426/55783396-3adace80-5aa6-11e9-96c5-0eef6c159fe3.jpg)
![IMG_20190409_085251](https://user-images.githubusercontent.com/10038426/55783397-3adace80-5aa6-11e9-990d-dbe557d83032.jpg)

**Comment by NSinclair94** [comment]
Already under control

**Comment by NSinclair94** [comment]
Boat is being repaired
