### ISSUE TITLE
Olive is missing the fin

### ISSUE THREAD

**Issue by Karlovik** [13enedict/CCRC#331]
### Boat name or ID
Olive

### Problem description
We took the fin out and put it on angels, so Olive it's missing it now

### Seat number(s) affected
specify the seats affected (or remove if not applicable)

### Photos of the issue
put a photo of the issue here (or remove if not applicable)

**Comment by NSinclair94** [comment]
Olive isn't supposed to be used now anyway, so it's not an issue
