### ISSUE TITLE
M3 blades unglued silicon grips

### ISSUE THREAD

**Issue by adrianalexa** [13enedict/CCRC#334]
### Boat name or ID
M3 blades

### Problem description
More than half of the M3 blades have the inner (inside hand) silicon grip unstuck. Grip is loose and impairs squaring/feathering. Grips got unstuck on different blades over the last week or so, so all blades need to be checked, re-glued.

Repair must happen before the bump start. 

Happy to do it if provided with instructions/materials

**Comment by NSinclair94** [comment]
I'm going to gather all the blades with this issue and do them Saturday
morning, can show you how is done if you like?

**Comment by adrianalexa** [comment]
Great, I should be free on Saturday 10am to 12pm (outings before 10am). What's best time for you?

**Comment by NSinclair94** [comment]
10am works for me.

**Comment by adrianalexa** [comment]
All M3 blades done. 
Used a new nozzle and quarter of the glue tube left - the bad left near the sculling blades.
