### ISSUE TITLE
W2 Blade Cracked

### ISSUE THREAD

**Issue by AubreeW** [13enedict/CCRC#34]
One of the bow side W2 blades has a crack in it after a run in with the bank today.  The bank won.

It's the bow side blade that only has one piece of blue tape instead of two.

**Comment by 13enedict** [comment]
I think we can consider this a part of #12 (W2 Blades). The current plan is to glue the W2 blades but I'm waiting to hear from @LauraClack on just how bad the situation is.

**Comment by 13enedict** [comment]
Blade has been sent off for repair.

**Comment by 13enedict** [comment]
Blade is back with Smoothie2 spoons
