### ISSUE TITLE
Cox boxes

### ISSUE THREAD

**Issue by nzia1** [13enedict/CCRC#38]
Only 3 of the new(ish) cox boxes upstairs seem to be charging/working.

**Comment by 13enedict** [comment]
The Cox boxes, batteries and microphones are now all labelled. If you can, could you specify which this applies to?

**Comment by 13enedict** [comment]
So, there have been a few issues with the chargers. I've had a look at the CoxBoxes and all seem to charge so I'm closing this for now.
