### ISSUE TITLE
St Mary's blades

### ISSUE THREAD

**Issue by CCRCJuniors** [13enedict/CCRC#41]
There is a split in one of the bowside blades from the st mary's set, looks like it might just need to be filled.

**Comment by 13enedict** [comment]
There are, I believe, two sets of blades for St. Marys. Could you confirm which set this applies to?

**Comment by CCRCJuniors** [comment]
I'm only aware of 1, it's the sweep set that are in the city boathouse, previously referred to as W5.

Cheers
Tammy

**Comment by JackLA** [comment]
It will be the newer set with Green handles and not the wooden set.

**Comment by CCRCJuniors** [comment]
That's correct it is the green handled set.

**Comment by 13enedict** [comment]
I've glued the blade and it's setting

**Comment by CCRCJuniors** [comment]
Thanks. Will it be ready by Sunday?

**Comment by 13enedict** [comment]
Sorry, I didn't get time to finish it but it should be usable. It's by the workshop area, if you could put it back there when they're done with it, that would be super.

**Comment by 13enedict** [comment]
Blade has been sanded down
