### ISSUE TITLE
heel ties

### ISSUE THREAD

**Issue by CCRCJuniors** [13enedict/CCRC#42]
Could we order some heel ties?  The heel ties in the coxed quads and some of the singles are looking frayed and we have little jnrs in the coxed quads, so real risk of rolling it.

Thanks!

**Comment by 13enedict** [comment]
We already have some.

**Comment by CCRCJuniors** [comment]
Hi Benedict,

Can you tell me where I can find the heel ties?

Thanks
Tammy

**Comment by 13enedict** [comment]
OK, just had a look, we have actually quite a small number - about four in the workshop, bottom shelf. I have 8 (I think) more pairs on the way.

**Comment by 13enedict** [comment]
Received extra pairs, I'll leave them in the boathouse tomorrow
