### ISSUE TITLE
Laurie - Bushes

### ISSUE THREAD

**Issue by AubreeW** [13enedict/CCRC#43]
A number of the bushes in Laurie are either missing or have been damaged.  Per Jack, they probably could all do with being replaced.  Can we get these ordered?  They could be inserted the next time the boat is derigged for travel.

**Comment by JackLA** [comment]
http://www.ekmpowershop7.com/ekmps/shops/janousekracing/carbon-lip-bush-1099-p.asp

**Comment by 13enedict** [comment]
This is perhaps a daft question but how many does Laurie need? I'll probably get that plus some spare

**Comment by JackLA** [comment]
5 per rigger and that will cover spares

**Comment by 13enedict** [comment]
Again, I know this is daft but just so I'm super clear, that's 40 bushes, right?

**Comment by JackLA** [comment]
That's going to be pricey... Let's get 20 and that should be more than
enough

**Comment by 13enedict** [comment]
Ordered 20 carbon lip bushes from Janousek

**Comment by 13enedict** [comment]
Received 20 carbon lip bushes from Janousek
