### ISSUE TITLE
Cox Box Chargers

### ISSUE THREAD

**Issue by AubreeW** [13enedict/CCRC#45]
I set aside (on the bar under the windows near the door) 3 chargers that seem to no longer be working.  Can we please order 3 more to replace them?  Thanks!

**Comment by 13enedict** [comment]
Inspected the chargers. Two are shorting out where the cable ties are. One has a broken pin. This represents £90 worth of charger so I'll look at repairing them

**Comment by 13enedict** [comment]
OK, I've repaired the chargers. I'll give them a test

**Comment by 13enedict** [comment]
So, two of them were completely broken. I've ordered replacements.
