### ISSUE TITLE
New tie downs for trailers and racks

### ISSUE THREAD

**Issue by ianwellwood** [13enedict/CCRC#46]
Hi Benedict,
Still don't understand GitHub - but here I am!
After recent wind related incidents - Please can you check securing straps on boat racks (internal and external) and those used on the towing trailer. If any look unsuitable please order replacements.

Thanks,
Ian

**Comment by umarndt** [comment]
straps needed: (in order of appearance)
boat: ---- straps needed: 
121---2
001---1
404---2
202---1
102---2
186---1
009---1
008---2
Dalley+quad on left of BH--2each
