### ISSUE TITLE
Redeham - 6 seat footplate

### ISSUE THREAD

**Issue by CCRCJuniors** [13enedict/CCRC#48]
6 seat - The tracks for the footplate are worn down and there is no traction for the screws at certain points so the footplate moves when any pressure is applied.  New tracks are required ASAP.

**Comment by 13enedict** [comment]
Just to clarify, are you taking about the footplate adjuster tracks? Is this only on the 6 seat?

**Comment by CCRCJuniors** [comment]
Hi Benedict 

Yes, that's correct, I didn't check them all but no complaints from the other girls yesterday. 

Cheers
Tammy

**Comment by 13enedict** [comment]
Are you sure this is the 6 seat on CAM321 Redeham and Weep?

I checked the seat; the footplate and adjuster tracks looked fine. The issue I could see was that somebody seems to have tightened it screws up needlessly tight.

It's worth mentioning that on the crenelation style adjuster tracks, as used on CAM321, it's necessary to correctly align the shoe plate with the adjuster track so that it locks in. Otherwise, there can be movement.

**Comment by CCRCJuniors** [comment]
Hi Benedict

I had a look at Redeham today and the centre track that the footplate attached too at the bottom is completely worn at the top. 
Also, the flat foot stretcher at the 4 seat needs to be replaced as the screws no longer fit, they have been pushed through completely by not being secured correctly.

Cheers
Tammy

**Comment by CCRCJuniors** [comment]
Hi Benedict

Just wanted to make sure you received my reply about the track in the
footwell at the 6 seat.  It needs to be fixed before WeHoRR on 5th March.

Thanks
Tammy

On 21 February 2016 at 22:40, CCRC Juniors <ccrcjuniors@gmail.com> wrote:

> Hi Benedict
>
> I had a look at Redeham today and the centre track that the footplate
> attached too at the bottom is completely worn at the top.
> Also, the flat foot stretcher at the 4 seat needs to be replaced as the
> screws no longer fit, they have been pushed through completely by not being
> secured correctly.
>
> Cheers
> Tammy
>
> Sent from my iPhone
>
> On 16 Feb 2016, at 13:20, Benedict <notifications@github.com> wrote:
>
> Are you sure this is the 6 seat on CAM321 Redeham and Weep?
>
> I checked the seat; the footplate and adjuster tracks looked fine. The
> issue I could see was that somebody seems to have tightened it screws up
> needlessly tight.
>
> It's worth mentioning that on the crenelation style adjuster tracks, as
> used on CAM321, it's necessary to correctly align the shoe plate with the
> adjuster track so that it locks in. Otherwise, there can be movement.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/13enedict/CCRC/issues/48#issuecomment-184680636>.
>
>


-- 
Tammy Finnigan
CCRC Junior Squad Co-ordinator
Mobile: 07920016476
