### ISSUE TITLE
Laurie Halifax stroke rate meter is malfunctioning

### ISSUE THREAD

**Issue by nzia1** [13enedict/CCRC#5]
It has been a week since I last coxed it but the rate kept jumping between 15-55 in steady state and up to 75 in race pieces. The cox box is fine as have used the same cox box in Tailwind and Redeham.

**Comment by 13enedict** [comment]
I tested this with the pre-2008 "M3" CoxBox and it seemed to be functioning correctly. Would you be able to retest this and if it is a problem, show me.

**Comment by 13enedict** [comment]
I'm closing this since the SRM seems to be working OK, let me know if there's still a problem!
