### ISSUE TITLE
Speakers and wiring in Doreen need replacing

### ISSUE THREAD

**Issue by Seb-Walker** [13enedict/CCRC#52]
These have been on and off over the last few weeks (when they get wet they get worse)  During Hammersmith Head the system failed.

I spoke to Jack who said we should just get new wiring and speakers.

**Comment by 13enedict** [comment]
Ordered replacement loom (not speakers). I suspect that most of it's fine but since this is our second boat, I'm taking the view that the old loom can be used for spares.

**Comment by CCRCJuniors** [comment]
Benedict, I actually think it might be the cox box headsets, I've heard
them crackling in most boats.  I used my own headset last week in Doreen
and the speakers were fine.  I am coxing in doreen tonight, will let you
know if there are problems.

On 9 March 2016 at 14:50, Benedict <notifications@github.com> wrote:

> Ordered replacement loom (not speakers). I suspect that most of it's fine
> but since this is our second boat, I'm taking the view that the old loom
> can be used for spares.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/13enedict/CCRC/issues/52#issuecomment-194328605>.
>



-- 
Tammy Finnigan
CCRC Junior Squad Co-ordinator
Mobile: 07920016476

**Comment by 13enedict** [comment]
OK, cool. I think you might be right. I have ordered some new headsets as
well.

**Comment by 13enedict** [comment]
I'm closing this as the CoxBoxes were in quite a poor state. If there is still crackling, please reopen.
