### ISSUE TITLE
Wheel on stroke's seat in Doreen is grinding

### ISSUE THREAD

**Issue by Seb-Walker** [13enedict/CCRC#53]
I think the ball-bearings are failing in one of the wheels in stroke's seat in Doreen.  It needs a new wheel.  Not sure which one.

**Comment by 13enedict** [comment]
Went to inspect the seat. The seat at stroke was not the stroke seat (no sensor magnet). The stroke seat (like most of the others) is missing.

**Comment by Seb-Walker** [comment]
Yes we put the seats on that way so we could row it back from Emma

**Comment by 13enedict** [comment]
Closing as we're giving up hope in seeing this seat again.
