### ISSUE TITLE
Redeham 7 seat rigger bolt missing

### ISSUE THREAD

**Issue by julielomas** [13enedict/CCRC#55]
The No 7 seat in Redeham lost the bolt on the rigger this morning.  We have added a temporary bolt to stop the gate falling out when we put the boat away, but it needs a proper replacement.

**Comment by LauraClack** [comment]
I didn't have time to check this on Sunday, the ladies need the boat Tuesday please can you have a look before then?

**Comment by 13enedict** [comment]
We don't have any rigger 13mm bolts (or at least the ones I bought have disappeared). I'll have to saw one down.

**Comment by 13enedict** [comment]
We have a bunch of top nuts in. Is this still a problem?

**Comment by julielomas** [comment]
No, it seems to be fine now - thanks though...



----Original Message----
