### ISSUE TITLE
Gate in the natural 2x 

### ISSUE THREAD

**Issue by CCRCJuniors** [13enedict/CCRC#56]
The gate on the stroke seat in bow side had broken and needs to be replaced.

**Comment by 13enedict** [comment]
I just had a look at the oarlock and it seems to be fine. Does this still need to be repaired?

**Comment by 13enedict** [comment]
I just had a look at the oarlock and it seems to be fine. Does this still need to be repaired?

**Comment by 13enedict** [comment]
I just had a look at the oarlock and it seems to be fine. Does this still need to be repaired?

**Comment by 13enedict** [comment]
I just had a look at the oarlock and it seems to be fine. Does this still need to be repaired?

**Comment by 13enedict** [comment]
I just had a look at the oarlock and it seems to be fine. Does this still need to be repaired?

**Comment by 13enedict** [comment]
I just had a look at the oarlock and it seems to be fine. Does this still need to be repaired?

**Comment by CCRCJuniors** [comment]
No, it can be closed, we replaced it yesterday morning before the girls raced. 
Thanks!
