### ISSUE TITLE
Jasmine - shoes 

### ISSUE THREAD

**Issue by CCRCJuniors** [13enedict/CCRC#57]
New shoes needed for Jasmine. Need the shoes to sit lower to allow them to fit under the wing rugger. Currently we have to remind be the tigger to adjust the footplate. Still need the shoes to be size 13.

Thanks!
Tammy

**Comment by CCRCJuniors** [comment]
Predictive text! Rugger/tigger = rigger. 
Remind = remove

**Comment by JackLA** [comment]
Let's try swapping a pair out the new Filippi

**Comment by CCRCJuniors** [comment]
Do you mean the quad?

**Comment by JackLA** [comment]
Yeah
