### ISSUE TITLE
CAM800 Laurie Halifax - 3 Rigger

### ISSUE THREAD

**Issue by AubreeW** [13enedict/CCRC#58]
One of the bushes has been stripped and the bolt and bush are in the rigger.  We we're able to get them separated last night so the rigger is on the workbench.  Nathalie has the new bushes and there are a few extras in the boat.

**Comment by 13enedict** [comment]
Is the problem that the damaged bush is stuck? Are the bushes Natalie has the spares that the club bought?

**Comment by AubreeW** [comment]
The screw is stuck in the bush so it won't come off the rigger.  I wasn't
able to get a good grip on the bush to get it off.  It is now definitely
damaged and will need to be replaced.  And the ones Nat has are the ones
you bought.  However, there are some spares in the boat if she doesn't have
a chance to get them to the boathouse before she goes on holiday.

**Comment by 13enedict** [comment]
OK, took out the bolt, chucked it and the bush away. No idea how a bush with no thread of stuck but there we go. I've put a new bolt, bush and nut on the rigger and it's ready to be fitted back on the boat.

**Comment by 13enedict** [comment]
(Loving the dog profile picture, by the way. I like to think that a dog is logging these issues.)
