### ISSUE TITLE
CAM001 Benny Powell steering plate

### ISSUE THREAD

**Issue by AubreeW** [13enedict/CCRC#59]
The shoe attached to the steering in the bow seat of Benny has come off.

**Comment by 13enedict** [comment]
Well, that's annoying, I was going to get a fancy steering plate for it but I guess we'll have to put a standard one on.

**Comment by 13enedict** [comment]
We don't have any compatible steering plates. I'll have to get one in

**Comment by 13enedict** [comment]
Got the new steering plate, put new shoes on it and put it together. I still need to put it in the boat and check the cable.

**Comment by 13enedict** [comment]
Fitted the shoe plate but there's still more to do until it is properly fitted. The foot stretcher must not be adjusted yet.

**Comment by 13enedict** [comment]
Changed the steering so that it uses a Bowden cable. Also adjusted steering so that you can turn equally in both directions. Still needs a new cable and the turning to be tightened up yet, though

**Comment by 13enedict** [comment]
New steering plate should be working OK now
