### ISSUE TITLE
Ontario Audio

### ISSUE THREAD

**Issue by colmcmurphy** [13enedict/CCRC#6]
There is no sound system in Ontario, i.e. cox boxes cannot be connected. The cox has to speak loudly when giving instructions. This can be problematic as the bow end does not always hear what has been said.

**Comment by 13enedict** [comment]
I'll bring this up at the next committee meeting.

**Comment by 13enedict** [comment]
I discussed this with the captain. He said that Ontario is never going to be used for racing and the club will soon be disposing of it. With that in mind, he does not want to fit audio. Sorry about that.
