### ISSUE TITLE
Jasmine Orriss rigger top-nut and washers missing

### ISSUE THREAD

**Issue by paul-eakins** [13enedict/CCRC#66]
Top-nut came undone while I was out yesterday, was left loose by someone after fiddling with the rigging?

I've left the gate on the workbench in the boathouse. Everything above the gate on the pin is missing (at the bottom of the reach).

**Comment by 13enedict** [comment]
Fitted new washers and top nut but not calibrated rigging. I'm going to replace the ageing gates as well

**Comment by 13enedict** [comment]
The riggers have been calibrated but the height stick wasn't high enough to fit. 

@JackLA would you mind taking a look? From the front, they possibly look a bit bent.

**Comment by 13enedict** [comment]
Fixed bent bowside rigger and calibrated
