### ISSUE TITLE
CAM013 Doreen leakage

### ISSUE THREAD

**Issue by pworth68** [13enedict/CCRC#7]
Water accumulating around the seat slider / anchor at position 5. Duct tape over the hull at this point presumably indicates known issue!!

**Comment by 13enedict** [comment]
This is a symptom of a problem that occurred during construction of the boat - the inside of the shell is split. We *may* fix it this weekend.

**Comment by Robllewellynjones** [comment]
I'll ping Jack an email about this today to what how it needs to be fixed and if there's a specific procedure that needs to be followed.

**Comment by 13enedict** [comment]
I spoke to Jack about this last night, if timing works, we'll take a look this weekend.

**Comment by pworth68** [comment]
Roger that too

**Comment by 13enedict** [comment]
OK, I stripped back the hull - it had been fixed previously with filler. We've now filled up the gap with epoxy which is setting. So, it should already be water tight.

**Comment by pworth68** [comment]
Well done maestro

From:  Benedict <notifications@github.com>
Reply-To:  13enedict/CCRC
<reply+00e9e5720b47181b9211eeab10884040cc3509eea8f5dfed92cf0000000112573c9d9
2a169ce06c26d12@reply.github.com>
Date:  Sunday, 8 November 2015 16:38
To:  13enedict/CCRC <CCRC@noreply.github.com>
Cc:  Paul Worth <pworth@doctors.org.uk>
Subject:  Re: [CCRC] Doreen leakage (#7)


OK, I stripped back the hull - it had been fixed previously with filler.
We've now filled up the gap with epoxy which is setting. So, it should
already be water tight.


Reply to this email directly or view it on GitHub
<https://github.com/13enedict/CCRC/issues/7#issuecomment-154839952> .

**Comment by 13enedict** [comment]
The painting has been finished off by Stämpfli.
