### ISSUE TITLE
New shoes for Empacher 1x

### ISSUE THREAD

**Issue by CCRCJuniors** [13enedict/CCRC#75]
Need a pair of size 13 shoes for Oliver.  We can fit them, just need to know if we have any or if not, can these be ordered.

Thanks
Tammy

**Comment by 13enedict** [comment]
Hmm. The Empacher 1x isn't a City boat. I'll have to bring this up with the Committee

**Comment by JackLA** [comment]
It's effectively a city boat with a city member in it. Keep the old shoes
and then when he stops using it we swap them again
