### ISSUE TITLE
Green Stampfli

### ISSUE THREAD

**Issue by pworth68** [13enedict/CCRC#77]
Totalled the bow by running it into the bank totally on purpose to give Benedict something useful to do :)

**Comment by JackLA** [comment]
Gripper will repair

**Comment by CCRCJuniors** [comment]
Girls are racing it at Nat schools in a couple of weeks and are training in it on Tue and Sun, do we have any idea when it will be repaired and if there is another lwt pair they could use in the meantime? 

Cheers
T

**Comment by JackLA** [comment]
I think Lisa had arranged for grip to do it

**Comment by pworth68** [comment]
Oops! Didn't think you'd see that jest Jack! Of course I didn't do it purpose! It was Shadbolt :)

**Comment by CCRCJuniors** [comment]
Actually the girls aren't out in the pair now until next Tuesday, as
they're at the Ball cup.
Could the pair be dropped off at Clare?? I had already spoken to Andy about
the bent back stays but sounds like the bows need looking at as well.

Happy to help to get the pair to Clare at the weekend or before but will
need a hand. Any offers??

Cheers

Lisa

**Comment by CCRCJuniors** [comment]
Thanks Lisa.  We will take it down to Clare either tonight after ergs if
Andy will be there or on Sat when we are loading the trailer.

Cheers
T

On 5 May 2016 at 08:25, Lisa Silk <lisasilk65@gmail.com> wrote:

> Actually the girls aren't out in the pair now until next Tuesday, as
> they're at the Ball cup.
> Could the pair be dropped off at Clare?? I had already spoken to Andy
> about the bent back stays but sounds like the bows need looking at as well.
>
> Happy to help to get the pair to Clare at the weekend or before but will
> need a hand. Any offers??
>
> Cheers
>
> Lisa
>
>
> On Thursday, 5 May 2016, CCRC Juniors <ccrcjuniors@gmail.com> wrote:
>
>> Girls are racing it at Nat schools in a couple of weeks and are training
>> in it on Tue and Sun, do we have any idea when it will be repaired and if
>> there is another lwt pair they could use in the meantime?
>>
>> Cheers
>> T
>> Sent from my iPhone
>>
>> On 4 May 2016, at 23:49, JackLA <notifications@github.com> wrote:
>>
>> Gripper will repair
>> On 4 May 2016 23:20, "pworth68" <notifications@github.com> wrote:
>>
>> > Totalled the bow by running it into the bank totally on purpose to give
>> > Benedict something useful to do :)
>> >
>> > —
>> > You are receiving this because you are subscribed to this thread.
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/13enedict/CCRC/issues/77>
>> >
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/13enedict/CCRC/issues/77#issuecomment-217027085>
>>
>>


-- 
Tammy Finnigan
CCRC Junior Squad Co-ordinator
Mobile: 07920016476

**Comment by 13enedict** [comment]
I'll be down there this afternoon / evening. I'd I see anyone loitering, I'll maybe get them to help me take it down.

**Comment by CCRCJuniors** [comment]
It's been repaired so this can be closed.
