### ISSUE TITLE
CAM012 Kieran West seat needs new wheels

### ISSUE THREAD

**Issue by pworth68** [13enedict/CCRC#8]
At position 5 as you know!

**Comment by 13enedict** [comment]
The wheels have been replaced with new ones.

However, I'm a touch worried about about the runners as well; I'm going to discuss whether they should be changed as well.

**Comment by pworth68** [comment]
Splendid effort :)

**Comment by 13enedict** [comment]
OK, I've discussed this now and the runners should be replaced. We have some in stock so @pworth68, @Robllewellynjones the next time we're using it, we'll need to spend a few minutes before the outing swapping the seat tracks out

**Comment by pworth68** [comment]
Roger that

**Comment by 13enedict** [comment]
We have eight new sets of seat tracks for KW which should make it much nicer to row in. We'll take some time prior to the next outing in KW to fit them, with 8+ people it should be quick

**Comment by 13enedict** [comment]
Done - changed all the wheels and seat tracks 👌🏻
