### ISSUE TITLE
Sculling blade inboard length

### ISSUE THREAD

**Issue by p-verrier** [13enedict/CCRC#82]
A lot of the club single sculling blades seem to have way too long inboard lengths -- I've tried 3 different pairs of sculls in the last few weeks and they've all had so much overlap it's almost impossible to scull with them. 

Are they like that for a reason? Or is it ok to change at least one pair to the 88-89cm inboard recommended on the wiki?

**Comment by JackLA** [comment]
It depends on which set, most will be set with 88 inboard (with blue
handles) as these are set for men's doubles quads and singles, the gyellow
handles are geared with 87-88 inboard and 285-6 overall length.

I wouldn't advise changing them as they are geared in sets for quads
however we need to have a check and make sure they are still geared in
sets. It's probably worth checking the span on the boat is not too tight.

**Comment by p-verrier** [comment]
The ones I'm talking about all have 'single scull' written on them (I thought the ones for quads all say 'quad'?).

The single scull blades seem to have been changed recently -- it's only been a problem in the last few weeks.

**Comment by JackLA** [comment]
OK single scull (blue handle) ones should all be 287 / 88 then - if not
change them

**Comment by 13enedict** [comment]
Blade configurations (at least to the best of my knowledge) can be found here: https://github.com/13enedict/CCRC/wiki/Blades
