### ISSUE TITLE
New shoes for The Natural

### ISSUE THREAD

**Issue by AubreeW** [13enedict/CCRC#87]
Do we have a spare pair of shoes that can be put in the bow of The Natural.  Hannah and I are racing in it next weekend and I'm essentially rowing feet out because the velcro is shot.  We're going out tomorrow so I'm happy to change them if you can tell me where they are.

**Comment by 13enedict** [comment]
What kind of shoes are in it now?

**Comment by AubreeW** [comment]
They're black. ??

**Comment by 13enedict** [comment]
Fitted size 8 Neaves adjustable
