### ISSUE TITLE
Redeham Steering Cable Wire

### ISSUE THREAD

**Issue by colmcmurphy** [13enedict/CCRC#88]
Wire snapped going around green dragon corner Saturday morning. 

Please could you fix good sir as soon as possible. Payment will be made with many diet cokes with lime and no ice.

**Comment by 13enedict** [comment]
OK, can fix tomorrow but I'll need the girls to get it out on trestles and then it will take about half an hour. I suggest that either everyone stands around for half an hour or they get it out prior to the outing, then row in CAM800 Laurie Halifax, then put it away after their outing. The second option is probably the one that would suit me as I can take my time. @colmcmurphy / @umarndt are you guys OK to arrange this between yourselves?

**Comment by umarndt** [comment]
I emailed the crew, asked for feedback. trying to get people out by 6pm for
fixing. We are going out with Redeham and Laurie, so will need 2 boats
(what is going on with Wholly? )
Ursula

**Comment by 13enedict** [comment]
Wholly is serviceable, I believe. Are you aware of anything stopping its use?

**Comment by umarndt** [comment]
not that I am aware of, just not being used at the moment for some reasons.
this would be an alternative if Redeham is not ready.
Ursula

**Comment by 13enedict** [comment]
I would suggest that you use CAM018 Wholly Spirited then but it's your outing

**Comment by 13enedict** [comment]
Replaced steering cable. It looks like the pulleys had been worn through to the metal as a result of the cable being too tight. Looks like we can't blame @colmcmurphy for this one ;)

**Comment by colmcmurphy** [comment]
Thank you good sir. Justice prevails!
