### ISSUE TITLE
Damage to rudder - Creme D'Or

### ISSUE THREAD

**Issue by feargalemurphy** [13enedict/CCRC#9]
Rudder damaged as trailer pushed out of boathouse. I think it happened then (or at least I only noticed then). Creme D'Or is not the best boat to store on upper rack of trailer as v difficult to move trailer out of boathouse (eg for circuits) - need at least 4 people . Gets caught in cross-girders. Any chance it can be moved back to lower rack where it was previously kept?

**Comment by 13enedict** [comment]
Just a quick update, the rack has been adjusted so that Creme d'Or will fit on the top, moving it to the bottom will mean that full rack needs to be adjusted. I'll update you when we've discussed it further.

**Comment by feargalemurphy** [comment]
ok cheers.

**Comment by 13enedict** [comment]
A further update which might actually be a ~~better~~ easier solution: I've removed the broken rudder and the tail fin. We don't have any rudders in stock that match the one removed so I'll keep it for now until we get a replacement.

For future reference, here's a photo of the rudder and fin
![img_0559](https://cloud.githubusercontent.com/assets/9012054/10996010/1f067742-8479-11e5-9989-5df9a28a2017.JPG)

**Comment by feargalemurphy** [comment]
Ok thanks. BTW, really impressed with your efforts on tidying up and
getting things in order around the boat house. I was thinking of tidying up
the weights we use for Monday circuits - did you have any preference for
how they are stored ?

Feargal

**Comment by 13enedict** [comment]
OK, I was planning on getting a replacement rudder but since there's no prospect of it becoming usable soon. I'm just going to close this issue. Thanks for reporting it.
